//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biometricroutine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIOMETRICOEntities : DbContext
    {
        public BIOMETRICOEntities()
            : base("name=BIOMETRICOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<biometricos> biometricos { get; set; }
        public virtual DbSet<divisiones> divisiones { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<finger_empleados> finger_empleados { get; set; }
        public virtual DbSet<logs_error> logs_error { get; set; }
        public virtual DbSet<marcaciones> marcaciones { get; set; }
        public virtual DbSet<marcaciones_app> marcaciones_app { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sap_empleados> sap_empleados { get; set; }
        public virtual DbSet<sap_marcaciones> sap_marcaciones { get; set; }
        public virtual DbSet<sociedades> sociedades { get; set; }
        public virtual DbSet<subdivisiones> subdivisiones { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
