//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biometricroutine
{
    using System;
    using System.Collections.Generic;
    
    public partial class biometricos
    {
        public int id { get; set; }
        public string ip { get; set; }
        public string modelo { get; set; }
        public string id_subdivision { get; set; }
        public Nullable<int> status { get; set; }
    }
}
