//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biometricroutine
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int id { get; set; }
        public string pernr { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string depto { get; set; }
        public string sucursal { get; set; }
        public string dni { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> status_empleado { get; set; }
    }
}
