//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biometricroutine
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcaciones_app
    {
        public int id { get; set; }
        public string pernr { get; set; }
        public string zatza { get; set; }
        public string ldate { get; set; }
        public string ltime { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public System.DateTime date { get; set; }
    }
}
