//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biometricroutine
{
    using System;
    using System.Collections.Generic;
    
    public partial class marcaciones
    {
        public int id { get; set; }
        public string data { get; set; }
        public string device { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> date_marcacion { get; set; }
    }
}
