//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Interface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class finger_empleados
    {
        public string pernr { get; set; }
        public int fingerIndex { get; set; }
        public int flag { get; set; }
        public string fingerData { get; set; }
        public int fingerLength { get; set; }
    }
}
