//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Interface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs_error
    {
        public int id { get; set; }
        public string platform { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string routine { get; set; }
        public string errorMessage { get; set; }
        public string ip { get; set; }
    }
}
