//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Interface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public int id_rol { get; set; }
        public int nivel_rol { get; set; }
    }
}
